In [1]:
a_set = set ([1,2,3,3,4,4,5]) # no order , no repitition
print a_set

set([1, 2, 3, 4, 5])


In [4]:
a_list = [1,2,3, "hello"]
a_tuple = (1,2,3,"hello")
print a_list
print a_tuple
print hash(a_tuple) # tuple can be passed through hash funtion
### WHAT IS HASH FUNCTION

[1, 2, 3, 'hello']
(1, 2, 3, 'hello')
2473311737894765252


In [6]:
b_list = a_list # no copy happens here # to create a copy, I have to go though a lot of operations scanning through the whole array using a lot of memory
# instead it just uses the same key to access the object in question
b_list[1] =7 
print a_list


[1, 7, 3, 'hello']


In [9]:
# BASIC PYTHON SYNTAX
# tuples, lists, dictionaries etc are iterable: can use for loops

for i in a_list:
    print i
    if i == "hello":
        print "Yo"
        
for i in range(2):
    print i+2

1
7
3
hello
Yo
2
3


In [10]:
a,b = 4,5
print a +b

9


In [11]:
print enumerate(["mridula","akhila"])
list(enumerate(["mridula","akhila"]))
for index,name in enumerate(["mridula","akhila"]):
    print index,name

[(0, 'mridula'), (1, 'akhila')]

In [24]:
# ZIP allows us to mix lists together or tear them apart
list1 = ['ned','joe','jill']
list2 = [1,2,3]
list3 = [7.0,8.8,9.2]
print zip(list1,list2,list3)
#you can do this with any number of lists

for i,j,k in zip(list1,list2,list3):
    print j +k
    # the above code avoided 3 lists
    
zipped_list =[['a',1,'hello'],['b',2,'world']]
zip(*zipped_list)

[('ned', 1, 7.0), ('joe', 2, 8.8), ('jill', 3, 9.2)]
8.0
10.8
12.2


[('a', 'b'), (1, 2), ('hello', 'world')]

In [20]:
# FUNCTIONS BASICS
def addTwoNumbers(x=0,y=0):
    return x+y
print addTwoNumbers(5,7)
print addTwoNumbers(y=5) # default y value is 0
# print addTwoNumbers(x=3,c=5) # throws error since c is undefined



12
5
1


In [22]:
# WHAT IF I WANT TO ADD MANY NUMBERS
def addManyNumbers( *args):
    ans = 0
    for i in args:
        ans = ans + i
    return ans

print addManyNumbers(1,2,3,4,5,6,7)
# print addManyNumbers("hello","hi") # throws error because ans = 0 -- integer
# print addManyNumbers([1,2,3]) # can't add list to int - 0
print addManyNumbers(*[1,2,3]) # * pulls out elements of list and adds them

28
6


In [25]:
def printKWargs(**kwargs): # this packs the keyword arguments into a dictionary called kwargs
    for key,value in kwargs.iteritems():
        print 'Argument name <%s> and value <%s> '%(str(key),str(value))
        
printKWargs(abc = "ABC", deg = "DEG")
# * is for lists ; ** is for dictionaries


Argument name <abc> and value <ABC> 
Argument name <deg> and value <DEG> 


In [28]:
#########################
# CLASS BASICS
#########################

# A class groups together some data and actions on it 
# let's create a class : Mazda
# It'll have 3 piecs of data: max_speed, color, and current speed
# we will also have some actions that operate on those pieces of data

class Mazda(object):
    
    def __init__(self,max_speed =100, color = 'red', current_speed =0):
        
        self.max_speed = max_speed
        self.color = color
        self.current_speed = current_speed
        
A = Mazda()
B = Mazda(max_speed = 160)

## What if we want to make a turbo-charged mazda, that works pretty much same way 
# but by default i want it to have a larger max speed

In [29]:
#############
# Modules
#############
# https://docs.python.org/2/library/itertools.html
# follow the url above for itertools: ned

import itertools
print list(itertools.combinations([1,2,3],2)) # n choose k 

[(1, 2), (1, 3), (2, 3)]


In [30]:
# Create your own module by placing a .py file inside a directory
# for ex, create a directory called my_module
# in it, put an empty __init__.py file
# and a file with the Mazda objects above

# Make sure that the directory above the my_odule is in the PYTHON_PATH variable, then you can do things like

# import my_module 

import sys
print sys.path

['', '/Users/mridulamaddukuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy-1.11.0-py2.7-macosx-10.6-x86_64.egg', '/Users/mridulamaddukuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python27.zip', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python2.7', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-darwin', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-mac', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-mac/lib-scriptpackages', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/lib-tk', '/Applications/Canopy.app/appdata/canopy-1.6.2.3262.macosx-x86_64/Canopy.app/C

In [36]:
#########################
# SCIPY and PYLAB

import scipy
import pylab # pylab is an interactive version of matplotlib; you can also import matplotlib

# Arrays are different than list because they contain only a single data type *****

# scipy/numpy provide basic array operations

a_zero = scipy.zeros((3,3))
a_ones = scipy.ones((3,3))
a_I = scipy.eye(3) # similar to matlab because they both use the same C base

print a_I
count = scipy.arange(10,dtype = float)
print count

print a_ones + a_ones
print a_ones * a_ones # elementwise multiplication
print a_ones.dot(a_ones) # a_one is an array object so it has many operations associated with it 

# https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html 
# useful links to do

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]
